### PR TITLE
patchesStrategicMerge is deprecated updating to patches

### PR DESCRIPTION
**Pull request by djdanielsson**
##### SUMMARY
when trying to deploy the operator on a k3s instance I was getting an error saying "patchesStrategicMerge is deprecated. Please use patches" I used the command 'kustomize edit fix' and it updated the file to look like this

### CODE REVIEW

**Review by rooftopcellist — APPROVED** [review]

**Comment by rooftopcellist** [comment]
@djdanielsson what is your kustomize version?

**Comment by djdanielsson** [comment]
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3

**Comment by rooftopcellist** [comment]
Odd, I just tried running `kustomize edit fix` with v5.4.0 and didn't get that diff.  Instead, all I got was:

```diff
$ git diff
diff --git a/kustomization.yaml b/kustomization.yaml
index 318f353..0415594 100644
--- a/kustomization.yaml
+++ b/kustomization.yaml
@@ -1,11 +1,10 @@
----
 apiVersion: kustomize.config.k8s.io/v1beta1
 kind: Kustomization
 resources:
-  - config/default
+- config/default
 
 namespace: galaxy
 
 images:
-  - name: quay.io/ansible/galaxy-operator
-    newTag: main
\ No newline at end of file
+- name: quay.io/ansible/galaxy-operator
+  newTag: main
```

**Comment by rooftopcellist** [comment]
same results when I test with kustomize v5.0.3 (v5.0.4 does not exist on kustomize release page)

**Comment by rooftopcellist** [comment]
Even after applying your changes, I still see the warning when running `make deploy`...

```
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
```

(with both v5.4.1 and v5.0.3)

**Comment by rooftopcellist** [comment]
@djdanielsson Nevermind me, PEBCAK, I hadn't saved on my editor when applying your changes.  This resolved the warning.  Thanks!

**Review by rooftopcellist — APPROVED** [review]

**Pull request merged**
