### PR TITLE
Deprecate pulp_settings in favor of extra_settings

### PR DESCRIPTION
**Pull request by Denney-tech**
##### SUMMARY

I think it would make sense for the galaxy-operator to behave more like the awx-operator for consistency's sake.  This adds `extra_settings:` to the CRD and the settings.py.j2 template. I didn't see any data manipulation in the awx-operator roles, so I presume none are needed here.

##### ADDITIONAL INFORMATION

[forum.ansible.com thread](https://forum.ansible.com/t/galaxy-operator-deprecating-pulp-settings-in-favor-of-extra-settings-ldap-support/4869?u=denney-tech)

Copied and modified documentation from awx-operator's extra_settings to here.

Depends on #98

### CODE REVIEW

**Comment by rooftopcellist** [comment]
@Denney-tech I definitely want something like this.  But there are a couple changes I think we'll need:
* We should mark the existing `pulp_settings` parameter as "Deprecated" in the CRD and CSV. But we can't remove it because that would cause CRD schema conflicts within the same apiVersion (tl;dr, nightmares for upgrades)
* We will also need the templating logic to have backwards compatibility for `pulp_settings`.

**Comment by Denney-tech** [comment]
I added a deprecation warning in an assertion step, but not sure what to do about the CRD/CSV.

This is backwards compatible with #98, and I wasn't intending to remove pulp_settings entirely. I think pulp_settings should stay for a handful of releases and maybe set a target removal date.

**Comment by Denney-tech** [comment]
So, just to clarify since I'm a little green when it comes to k8s operators; we can't remove pulp_settings (or any other parameter) from a CRD unless we change the version, such as: [galaxy_v1beta1_galaxy_crd.yaml#L15](https://github.com/ansible/galaxy-operator/blob/main/config/crd/bases/galaxy_v1beta1_galaxy_crd.yaml#L15)?

Does the CSV have to match the CRD? I don't see a similar version spec in the CSV.

**Comment by Denney-tech** [comment]
@rooftopcellist fixed the crd error, a mistake in the csv, and resolved the merge conflict that was present.

**Comment by Denney-tech** [comment]
Muddied the water a bit in my fork, so I'm closing these PR's while I cleanup.

**Pull request closed without merging**
